WIP: D- 2935 node grouping in fcose layout dara UI
causalens/dara-ui pull request #106
Opened 2024-05-08 16:58 UTC by patricia-causalens

WIP

## Motivation and Context

## Implementation Description

## Any new dependencies Introduced

## How Has This Been Tested?

## PR Checklist:

- [ ] I have implemented all requirements? (see JIRA, project documentation).
- [ ] I am not affecting someone else's work, If I am, they are included as a reviewer.
- [ ] I have added relevant tests (unit, integration or regression).
- [ ] I have added comments to all the bits that are hard to follow.
- [ ] I have added/updated Documentation.
- [ ] I have updated the appropriate changelog with a line for my changes.

## Screenshots (if appropriate):

2024-05-14 13:07 UTC, krzysztof-causalens requested changes
I've had a look through the code so far - will try to find some time to play with it locally soon as well. Code looks good in general, great job! I found some minor style/performance issues below

2024-05-14 13:07 UTC, krzysztof-causalens commented on packages/ui-causal-graph-editor/src/shared/rendering/utils.tsx
> +}
That's a fairly inefficient implementation of the search, as you're effectively searching for it twice. Can you think of a more efficient implementation? Try to reduce the number of iterations over the lists/objects, and make sure to stop the search whenever an item is found.

2024-05-15 16:43 UTC, patricia-causalens commented on packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx
> +        // const nodeAttributes = state.graph.getNodeAttributes(nodeId);
oops removed

2024-05-15 16:50 UTC, patricia-causalens commented on packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx
> +                                    )}
good point fixed

2024-05-15 16:52 UTC, patricia-causalens commented on packages/ui-causal-graph-editor/src/graph-viewer/custom-layout.stories.tsx
Good point, moved

2024-05-15 16:54 UTC, patricia-causalens commented on packages/ui-causal-graph-editor/src/shared/rendering/edge/definitions.tsx
> +    collapsedEdges?: number;
Good point, agree

2024-05-24 10:13 UTC, claudiawestby commented
getting weird behavior when all the nodes within the same group (towards end of video)
https://github.com/causalens/dara-ui/assets/98322280/eccecb4e-ca07-4850-ac64-82126ccc52ac

2024-06-04 08:33 UTC, patricia-causalens commented
> getting weird behavior when all the nodes within the same group (towards end of video) https://github.com/causalens/dara-ui/assets/98322280/eccecb4e-ca07-4850-ac64-82126ccc52ac

Hi @claudiawestby , thanks for the feedback, I have addressed the issue for now to not allow you to remove the last node in a group and show a warning instead (we can change this behaviour in the future, it was easier to implement for now). Could you have another look and let me know if it seems ok?

2024-06-04 10:33 UTC, patricia-causalens commented
Merging since will have another PR soon for d3 so can deal with any further issues that come up in that one

2024-06-04 10:33 UTC, merged